"""Write a machine-readable manifest for downloaded and simulated datasets."""

from __future__ import annotations

from datetime import datetime, timezone
import json

from src.config import (
    CLIMATE_API_URL,
    CLIMATE_PROVIDER,
    CLIMATE_REANALYSIS,
    CLIMATE_TIMEZONE,
    DATA_PROCESSED,
    GADM_LAYER,
    GADM_URL,
    GADM_VERSION,
    RANDOM_SEED,
    ensure_data_dirs,
)


def write_data_manifest(extra: dict | None = None) -> None:
    """Persist source, version, access time, and license notes."""
    ensure_data_dirs()
    payload = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "random_seed": RANDOM_SEED,
        "boundaries": {
            "dataset": "GADM",
            "version": GADM_VERSION,
            "layer": GADM_LAYER,
            "url": GADM_URL,
            "unit_definition": (
                "GADM Admin-2 polygons for Togo. These are prefectures, not the "
                "official Ministry of Health / DHIS2 health districts."
            ),
            "license_note": (
                "GADM terms apply. Review https://gadm.org/license.html before redistribution."
            ),
        },
        "climate": {
            "provider": CLIMATE_PROVIDER,
            "reanalysis": CLIMATE_REANALYSIS,
            "endpoint": CLIMATE_API_URL,
            "timezone": CLIMATE_TIMEZONE,
            "spatial_support": (
                "One in-polygon representative point per Admin-2 unit (not a zonal mean "
                "over the polygon)."
            ),
            "native_download": "daily",
            "analysis_resolution": "calendar-month aggregates",
        },
        "incidence": {
            "type": "simulated",
            "file": "togo_malaria_incidence_simulated.csv",
            "not_a_source": [
                "Malaria Atlas Project (MAP) does not provide monthly district incidence here.",
                "No DHIS2 / SNIS / PNLP case counts are included in this repository.",
            ],
            "license": "Generated by this repository (Apache-2.0 code; simulated values are not observational data).",
        },
    }
    if extra:
        payload.update(extra)
    path = DATA_PROCESSED / "data_manifest.json"
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
